### ISSUE TITLE
Original  body disappears with all inventory in death

### ISSUE THREAD

**Issue by cjser** [Ladysnake/Dissolution#109] opened 2019-01-07 20:52 UTC
Every time I die the body disappears and every npc and monster in a radius disappears or became invisible I don't know because sometimes I see and hears them

**Comment by cjser** [comment] 2019-01-07 20:56
I come a little later to where I die and the inventory is there now floating. But no body

**Comment by RiverLeviathan** [comment] 2019-01-07 20:56
We are already aware of this bug, but thanks for reporting it. Duplicate of #107.

**Closed** 2019-01-07 20:56 UTC
Labels: duplicate
