### ISSUE TITLE
Baby Zombies Burn at Daylight

### ISSUE THREAD

**Issue by mario384** [Ladysnake/Dissolution#36] opened 2018-02-25 19:13 UTC
Pretty simple, when possessing a baby zombie, they burn during the day, despite the regular ones not doing so.

**Comment by Pyrofab** [comment] 2018-02-25 19:16
Pretty much intended behaviour, I considered that people would have quark installed more often than not. I will probably attempt to make something a bit more clever though.

**Comment by Pyrofab** [comment] 2018-07-26 22:38
Fixed in Dissolution Resurrection

**Closed by Pyrofab** 2018-07-26 22:38 UTC
Labels: bug
